fixed deploy

diff --git a/.github/workflows/node-pipeline.yml b/.github/workflows/node-pipeline.yml
--- a/.github/workflows/node-pipeline.yml
+++ b/.github/workflows/node-pipeline.yml
@@ -29,6 +29,10 @@ jobs:
     needs: build
     runs-on: self-hosted 
     steps:
+      - name: Login to docker hub
+        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
+        id: login-deploy-docker-hub
+
       - name: Pull image from docker hub
         run: docker pull zyffyz/ci-cd:latest 
         id: pull-image
@@ -36,7 +40,7 @@ jobs:
       - name: Delete old container
         run: docker rm -f nodejs-app-container
         id: delete-container  
-        
+
       - name: Run Docker Container
         run: docker run -d -p 5000:5000 --name nodejs-app-container -e DB_HOST='${{ secrets.DB_HOST }}' DB_PASSWORD='${{ secrets.DB_PASSWORD }}' DB_CLUSTER_NAME='${{ secrets.DB_CLUSTER_NAME }}'  zyffyz/ci-cd
         id: run-container
@@ -65,18 +69,28 @@ jobs:
             echo "❌ Failed to publish Docker Image!"
             exit 1
           fi
+
+          if [ ${{ steps.login-deploy-docker-hub.outcome }} == 'success' ]; then
+            echo "✅ Successfully logged in to Docker Hub!"
+          else
+            echo "❌ Failed to log in to Docker Hub!"
+            exit 1
+          fi
+
           if [ ${{ steps.pull-image.outcome }} == 'success' ]; then
             echo "✅ Successfully pulled Docker Image!"
           else
             echo "❌ Failed to pull Docker Image!"
             exit 1
           fi
+
           if [ ${{ steps.delete-container.outcome }} == 'success' ]; then
             echo "✅ Successfully deleted old container!"
           else
             echo "❌ Failed to delete old container!"
             exit 1
           fi
+
           if [ ${{ steps.run-container.outcome }} == 'success' ]; then
             echo "✅ Successfully deployed container!"
           else
