docker ec2

diff --git a/.github/workflows/node-pipeline.yml b/.github/workflows/node-pipeline.yml
--- a/.github/workflows/node-pipeline.yml
+++ b/.github/workflows/node-pipeline.yml
@@ -13,50 +13,74 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v3 # Checks out the code from the repository
 
-      - name: Set up Node.js
-        uses: actions/setup-node@v3
-        with:
-          node-version: latest
+      - name: Login to docker hub
+        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
+        id: login-docker-hub
 
-      - name: Install dependencies with npm
-        run: npm install
-        continue-on-error: false
-        id: install-dependencies
+      - name: Build Docker Image
+        run: docker build -t zyffyz/ci-cd  .
+        id: build-image
 
-      - name: Install Railway CLI
-        run: npm i -g @railway/cli
-        continue-on-error: false
-        id: install-railway-cli
+      - name: Publish Image to docker hub
+        run: docker push zyffyz/ci-cd:latest
+        id: publish-image
+
+  deploy:
+    needs: build
+    runs-on: self-hosted 
+    steps:
+      - name: Pull image from docker hub
+        run: docker pull zyffyz/ci-cd:latest 
+        id: pull-image
+
+      - name: Delete old container
+        run: docker rm -f nodejs-app-container
+        id: delete-container  
         
-      - name: Deploy to Railway
-        run: railway up --service node-dockerize-cicd
-        env:
-          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
-        continue-on-error: false
-        id: deploy-to-railway
+      - name: Run Docker Container
+        run: docker run -d -p 5000:5000 --name nodejs-app-container -e DB_HOST='${{ secrets.DB_HOST }}' DB_PASSWORD='${{ secrets.DB_PASSWORD }}' DB_CLUSTER_NAME='${{ secrets.DB_CLUSTER_NAME }}'  zyffyz/ci-cd
+        id: run-container
 
       # Success/Failure message after key steps
       - name: Check Success/Failure Messages
         if: always()
         run: |
-          if [ ${{ steps.install-dependencies.outcome }} == 'success' ]; then
-            echo "✅ Dependencies installed successfully!"
+          if [ ${{ steps.login-docker-hub.outcome }} == 'success' ]; then
+            echo "✅ Successfully logged in to Docker Hub!"
           else
-            echo "❌ Failed to install dependencies!"
+            echo "❌ Failed to log in to Docker Hub!"
             exit 1
           fi
 
-          if [ ${{ steps.install-railway-cli.outcome }} == 'success' ]; then
-            echo "✅ Railway CLI installed successfully!"
+          if [ ${{ steps.build-image.outcome }} == 'success' ]; then
+            echo "✅ Successfully built Docker Image!"
           else
-            echo "❌ Railway CLI installation failed!"
+            echo "❌ Failed to build Docker Image!"
             exit 1
           fi
 
-          if [ ${{ steps.deploy-to-railway.outcome }} == 'success' ]; then
-            echo "✅ Successfully deployed to Railway!"
+          if [ ${{ steps.publish-image.outcome }} == 'success' ]; then
+            echo "✅ Successfully published Docker Image !"
           else
-            echo "❌ Deployment to Railway failed!"
+            echo "❌ Failed to publish Docker Image!"
+            exit 1
+          fi
+          if [ ${{ steps.pull-image.outcome }} == 'success' ]; then
+            echo "✅ Successfully pulled Docker Image!"
+          else
+            echo "❌ Failed to pull Docker Image!"
+            exit 1
+          fi
+          if [ ${{ steps.delete-container.outcome }} == 'success' ]; then
+            echo "✅ Successfully deleted old container!"
+          else
+            echo "❌ Failed to delete old container!"
+            exit 1
+          fi
+          if [ ${{ steps.run-container.outcome }} == 'success' ]; then
+            echo "✅ Successfully deployed container!"
+          else
+            echo "❌ Failed to deploy container!"
             exit 1
           fi
         continue-on-error: false
